apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-visualizer-fe
  namespace: visualizer
  labels:
    app: k8s-visualizer-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-visualizer-fe
  template:
    metadata:
      labels:
        app: k8s-visualizer-fe
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101        # nginx default non-root UID (nginx:alpine)
        runAsGroup: 101
        fsGroup: 101
      imagePullSecrets:
        - name: dockerhub-credentials
      containers:
        - name: fe
          image: nkd7059181/k8s-visualizer-fe:latest
          ports:
            - containerPort: 80
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false  # nginx cần ghi tmp files
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
