apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: visualizer-project
  namespace: argocd
spec:
  sourceRepos:
    - 'https://github.com/NguyenKhanhDuy2703/k8s-learn-pratice'

  destinations:
    # namespace cho app thực tế
    - namespace: visualizer
      server: https://kubernetes.default.svc
    # namespace cho ArgoCD App-of-Apps (root-app deploy vào đây)
    - namespace: argocd
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRole
    - group: 'rbac.authorization.k8s.io'
      kind: ClusterRoleBinding

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'