apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly

  policy.csv: |
    # role developer: được xem và sync app trong project visualizer
    p, role:developer, applications, get,      visualizer/*, allow
    p, role:developer, applications, sync,     visualizer/*, allow
    p, role:developer, applications, action/*, visualizer/*, allow
    p, role:developer, logs,         get,      visualizer/*, allow

    # Không cho developer xóa app, sửa/xóa project
    p, role:developer, applications, delete,   visualizer/*,  deny
    p, role:developer, applications, override, visualizer/*,  deny
    p, role:developer, projects,     update,    visualizer,   deny
    p, role:developer, projects,     delete,    visualizer,   deny
    p, role:developer, exec,         create,    visualizer/*, deny

    # Gán user developer vào role developer
    g, developer, role:developer