apiVersion: v1
kind: Service
metadata:
  name: k8s-visualizer-fe
  namespace: k8s-visualizer
spec:
  type: NodePort
  selector:
    app: k8s-visualizer-fe
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090     # truy cập: http://<node-ip>:30090
      protocol: TCP
