name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "application/be/**"
      - "!application/be/**/*.yaml"
      - "!application/be/**/*.yml"

jobs:
  call-docker-build:
    uses: ./.github/workflows/template-docker-build.yaml
    with:
      working_directory: ./application/be
      image_name: k8s-visualizer-be
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  call-update-manifest:
    needs: [call-docker-build]
    uses: ./.github/workflows/template-update-manifest.yaml
    with:
      image_name: k8s-visualizer-be
      manifest_file_path: ./cd-application/be/deployment.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      GH_PAT: ${{ secrets.GH_PAT }}
