name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "application/fe/**"

jobs:
  call-docker-build:
    uses: ./.github/workflows/template-docker-build.yaml
    with:
      working_directory: ./application/fe
      image_name: k8s-visualizer-fe
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  call-update-manifest:
    needs: [call-docker-build]
    uses: ./.github/workflows/template-update-manifest.yaml
    with:
      image_name: k8s-visualizer-fe
      manifest_file_path: ./cd-application/k8s-visualizer/fe-deployment.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
